story_6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('updatestatus.urls')),
    path('accounts/', include('thelogin.urls')),
]

thelogin/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name="thelogin"
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', views.registerViews, name='register'),
    path('logout/', LogoutView.as_view(next_page='thelogin:login'), name='logout'), 
]
# template_name='registration/login.html'

updatestatus/urls.py
from django.urls import path
from . import views

app_name="updatestatus"
urlpatterns = [
    path('', views.index, name='index'),
    path('onlypage/', views.onlypage, name='onlypage'),
]

thelogin/models.py
from django.db import models

# Create your models here.

updatestatus/models.py
from django.db import models

# Create your models here.

class UpdateStatus(models.Model):
    status = models.CharField(max_length = 300, default="")
    waktu = models.DateTimeField(auto_now_add=True, editable=False, null=False, blank=False)

updatestatus/forms.py
from django import forms
from .models import UpdateStatus
from django.forms import widgets

class UpdateForm(forms.ModelForm):

    class Meta():
        model = UpdateStatus
        fields = {'status'}
        widgets = {
            'status' : forms.Textarea(attrs={'cols':10, 'rows': 5}),
        }

    def __init__(self, *args, **kwargs):
        super(UpdateForm,self).__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

thelogin/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def registerViews(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('thelogin:login')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form':form})

updatestatus/views.py
from django.shortcuts import render,redirect
from .models import UpdateStatus
from .forms import UpdateForm
from django.contrib.auth.decorators import login_required


# Create your views here.
# @login_required
def index(request):
    if request.method == "POST":
        form = UpdateForm(request.POST)
        if form.is_valid():
            status = form.save(commit=False)
            status.save()
            return redirect('updatestatus:index')
    else:
        form = UpdateForm()
    status = UpdateStatus.objects.all().order_by('-waktu')
    return render(request, 'UpdateYuk.html', {'form' : form, 'status' : status})

# @login_required
def onlypage(request):
    return render(request,'Jafaskrip.html')

thelogin/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/ajaks.css' %}"/>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <title>akbarrafs - dashboard</title>
</head>
<body>
    
</body>
</html>

thelogin/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <title>akbarrafs - logout</title>
</head>
<body>
    
</body>
</html>

thelogin/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/universall.css' %}"/>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <title>akbarrafs - register</title>
</head>
<body>
    <header>
        {% block navbar %}
        {% with current_nav='register' %}
        {% include 'navbar/navbar.html' %}

        {% endwith %}
        {% endblock navbar %}
    </header>
    <section>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary">Register</button>
        </form>
    </section>
</body>
</html>

updatestatus/templates/Jafaskrip.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <link rel="icon" href="{% static 'image/logo.png' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/universall.css' %}"/>
        <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="https:/resources/demos/style.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        
        <title>
            Mari Bercerita - Profile
        </title>
    </head>
    <body class="light">
        <header>
            {% block navbar %}
            {% with current_nav='jafaskrip' %}
            {% include 'navbar/navbar.html' %}

            {% endwith %}
            {% endblock navbar %}
        </header>
        <section>
            <div class="container-fluid kontainer">
                <div class="row">
                    <div class="col-6">
                            <button type="button" class="btn btn-primary gelapmode" id="darkmode">Dark Mode</button>
                        <h1 class="saya">Saya.</h1>
                        <p class="deskripsi">
                            Perkenalkan, nama panggilan saya Akbar.
                            saya adalah mahasiswa Fasilkom yang salah masuk jurusan.
                            Aslinya saya pengen masuk Sistem Informasi tapi malah masuk Ilmu Komputer.
                            Ceritanya bermula dari sini, waktu saya udah mau lulus, saya masih ngga tau
                            harus milih jurusan apa dan juga waktu itu saya cukup ngga peduli sama yang
                            namanya milih-milih kuliah. saya inget waktu itu milih ilmu komputer karena
                            pengen ngerti komputer biar bisa bisnis dalam bidang it, seperti bapak saya.
                            Setelah itu ambil s2 bisnis, bedanya adalah bapak saya s2 nya juga komputer. 
                            Tapi ternyata ada jurusan SI yang bisa lebih cepat mendapat ilmu komputer sekaligus bisnis.
                            Udah masuk gini, kepikiran sih buat pindah jurusan ke sistem informasi, tapi ternyata ribet.
                            Akhirnya saya berusaha sekuat tenaga untuk survive.
                            Salah satu agar saya bisa survive di Fasilkom adalah dengan cara mengerjakan tugas yang sudah diberikan dosen dengan baik, semoga saya bisa lulus memuaskan dan bisa dapetin S.Kom<br>
                            Aamiin. 
                        </p>
                    </div>
                    <div class="col-6">
                        <div id="accordion">
                            <h3 class="aktivitas">Aktivitas</h3>
                            <div>
                                <p>
                                    Aktivitas yang sedang saya jalani adalah menjalani hari-hari sebagai
                                    mahasiswa ilmu komputer sambil beripkir bagaimana caranya saya bisa
                                    cepat-cepat memiliki bisnis untuk melanjutkan kehidupan.
                                </p>
                            </div>
                            <h3 class="pengalaman">Pengalaman Organisasi/Kepanitiaan</h3>
                            <div>
                                <p>
                                    Perngalaman-pengalaman:
                                </p>
                                <ul>
                                    <li>STAFF Perlengkapan UIAW 2018</li>
                                    <li>STAFF Kampanye Pemira 2018</li>
                                    <li>STAFF SBF BEM Senbud 2018</li>
                                    <li>Kontingen Taekwondo OLIM 2018</li>
                                    <li>Kontingen Film UIAW 2018</li>
                                    <li>STAFF Games CGT 2019</li>
                                    <li>STAFF Direct Marketing Compfest 2019</li>
                                </ul>
                            </div>
                            <h3 class="prestasi">Prestasi</h3>
                            <div>
                                <p>
                                    Prestasi
                                </p>
                                <ul>
                                    <li> Medali Perak - Indonesia Youth and Sport Festival Taekwondo</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    
                </div>
            </div>
        </section>
        <script src="{% static 'js/Jafaskrip.js' %}"></script>
    </body>
</html>

updatestatus/templates/UpdateYuk.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <link rel="icon" href="{% static 'image/logo.png' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/universall.css' %}"/>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <title>
            Mari Bercerita - Home
        </title>
    </head>
    <body>
        <header>
            {% block navbar %}
            {% with current_nav='updateyuk' %}
            {% include 'navbar/navbar.html' %}

            {% endwith %}
            {% endblock navbar %}
        </header>
        <section>
            <div class="container-fluid text-center kontener">
                {% if user.is_authenticated %}
                <h1 class="saya">
                    Hello {{ user.username }}, What's on your mind ?
                </h1>
                {% else %}
                <h1 class="saya">
                    Hello, What's on your mind ?
                </h1>
                {% endif %}
                <form method="POST" class="kotakan">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="button submit" class="btn btn-primary">Submit</button>
                </form>
                <hr>
                {% if user.is_authenticated %}
                <div class="overflow-auto">
                    {% for status in status %}
                    <p class="hasil">
                        {{ user.username }} said: {{ status.status }} || Posted on: {{ status.waktu }}
                    </p>
                    {% endfor %}
                </div>
                {% else %}
                <div class="overflow-auto">
                    {% for status in status %}
                    <p class="hasil">
                        Someone said: {{ status.status }} || Posted on: {{ status.waktu }}
                    </p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </section>
    </body>
</html>

updatestatus/templates/navbar/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="#">
            <img src="{% static 'image/logo.png' %}">
        </a>
        <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="{% if current_nav == 'updateyuk' %} nav-link active {% endif %} nav-link" href="{% url 'updatestatus:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="{% if current_nav == 'jafaskrip' %} nav-link active {% endif %} nav-link" href="{% url 'updatestatus:onlypage' %}">Profile</a>
            </li>
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="{% if current_nav == 'login' %} nav-link active {% endif %} nav-link" href="{% url 'thelogin:login' %}">Dashboard</a>
                {% else %}
                <a class="{% if current_nav == 'login' %} nav-link active {% endif %} nav-link" href="{% url 'thelogin:login' %}">Login</a>
                {% endif %}
            </li>
          </ul>
        </div>
      </nav>